### ISSUE TITLE
pango markup & motd

### ISSUE THREAD

**Issue by Fandekasp** [Airblader/dotfiles-manjaro#10]
Hi Airblader,

Any reason why you removed the --pango_markup flag to the mode definition? It looked pretty nice before.
Strangely, when trying to readd it myself, it gets a ugly red background color by default, wondering it... will search the doc :)

**Comment by Fandekasp** [comment]
got it for the red background, needed to update `bar { colors { binding_mode } }`  with `$transparent $transparent $yellow`

**Comment by Fandekasp** [comment]
Also, would you mind sharing your MOTD example with w3m ?
![screenshot](https://camo.githubusercontent.com/7da062cb011d81a3551cd34ee2d33886ee6b2e06/687474703a2f2f692e696d6775722e636f6d2f7938735a45366f2e6a7067)

Would love to do something similar

**Comment by Airblader** [comment]
> Any reason why you removed the --pango_markup flag to the mode definition? It looked pretty nice before.

I just like it being simple. My entire setup is much simpler now. :-) 

> Also, would you mind sharing your MOTD example with w3m ?

motd as in message of the day? Where do you see that? I don't have that. :-)

**Comment by Fandekasp** [comment]
I see :)
Sorry, I thought that was an motd, but I was wrong. In your screenshot above, how did you generate the image and text in the bottom right terminal ?

**Comment by Airblader** [comment]
That's neofetch!  https://github.com/dylanaraps/neofetch

**Comment by Fandekasp** [comment]
duh, didn't spend enough time look through your dependency list. Thx man!

**Comment by Airblader** [comment]
Anytime!
