### ISSUE TITLE
compton errors

### ISSUE THREAD

**Issue by bhepple** [Airblader/dotfiles-manjaro#14]
Not sure if the errors are important, but your .compton.conf file prints this:
```
$ compton
[     0.15 ] error    2 BadValue     request   20 minor    0 serial    236: "BadValue (integer parameter out of range for operation)"
[     0.15 ] error    2 BadValue     request   20 minor    0 serial    237: "BadValue (integer parameter out of range for operation)"
... <many more of the same>
```

**Comment by Airblader** [comment]
Hi,

thanks for reporting this (still baffles me that people submit issues and PRs for my dotfiles!). I believe I had that with the "old" compton, and even there it wasn't really an issue (I don't recall any details, though). On my machine right now with the "new" compton (fork) I'm only getting (different) warningd about deprecated flags, but not this. I'll close this for now, but again, I appreciate you reporting it and if you do find something that is wrong I'd be happy to hear about it!

**Comment by bhepple** [comment]
I should have mentioned I'm on compton-0.1-0.3.beta3.fc29.x86_64
(fedora-29, obviously) - is that 'old'?

Cheers


Bob

**Comment by Airblader** [comment]
Yeah, I believe so.
