### ISSUE TITLE
compton log

### ISSUE THREAD

**Issue by INGCRENGIFO** [Airblader/dotfiles-manjaro#15]
# Code deprecated
[ 08/03/2019 23:53:13.649 parse_config_libconfig WARN ] Option `no-dock-shadow` is deprecated, and will be removed. Please use the wintype option `shadow` of `dock` instead.
[ 08/03/2019 23:53:13.649 parse_config_libconfig WARN ] Option `no-dnd-shadow` is deprecated, and will be removed. Please use the wintype option `shadow` of `dnd` instead.
[ 08/03/2019 23:53:13.649 parse_config_libconfig WARN ] vsync option will take a boolean from now on. "opengl-swc" is interpreted as "true" for compatibility, but this will stop working soon
[ 08/03/2019 23:53:13.649 parse_config_libconfig WARN ] glx-swap-method has been deprecated since v6, your setting "undefined" should be removed.
[ 08/03/2019 23:53:13.649 parse_config_libconfig WARN ] "clear-shadow" is removed as an option, and is always enabled now. Consider removing it from your config file
[ 08/03/2019 23:53:13.649 parse_config_libconfig WARN ] "paint-on-overlay" has been removed as an option, and is enabled whenever possible
[ 08/03/2019 23:53:13.649 parse_config_libconfig WARN ] "alpha-step" has been removed, compton now tries to make use of all alpha values
[ 08/03/2019 23:53:13.731 swopti_init WARN ] --sw-opti is going to be deprecated. If you get real benefits from using this option, please open an issue to let us know.

**Comment by INGCRENGIFO** [comment]
I have modified the file in this way to fix it.

```
backend = "glx";
vsync = true;

shadow = true;
dock-shadow = false;
dnd-shadow = false;

shadow-radius = 10;
shadow-offset-x = -5;
shadow-offset-y = 0;
shadow-opacity = 0.8;
shadow-red = 0.11;
shadow-green = 0.12;
shadow-blue = 0.13;
shadow-exclude = [
  "name = 'Notification'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'i3-frame'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_STICKY'",
  "!I3_FLOATING_WINDOW@:c"
];
shadow-ignore-shaped = true;

blur-background = false;
blur-background-fixed = true;
blur-kern = "7x7box";
blur-background-exclude = [
  "class_g = 'i3-frame'",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

# Duplicating the _NET_WM_STATE entries because compton cannot deal with atom arrays :-/
opacity-rule = [
  "97:class_g = 'Termite' && !_NET_WM_STATE@:32a",

  "0:_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[1]:32a = '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[2]:32a = '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[3]:32a = '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[4]:32a = '_NET_WM_STATE_HIDDEN'",

  "90:_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[1]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[2]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[3]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[4]:32a = '_NET_WM_STATE_STICKY'"
];

fading = false;
fade-delta = 7;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-exclude = [];

mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
dbe = false;
glx-no-stencil = true;
glx-copy-from-front = false;
unredir-if-possible = false;
focus-exclude = [];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [];

wintypes: {
    tooltip = { fade = true; shadow = false; opacity = 1.00; focus = true; };
};

```

**Comment by Airblader** [comment]
If you would like to send a quick PR, that would be appreciated :-)

**Comment by Airblader** [comment]
Actually just fixed it myself real quick!
