### ISSUE TITLE
A question about MC-244164

### ISSUE THREAD

**Issue by magneticflux-** [Airblader/dotfiles-manjaro#18]
Sorry for tracking you down this way, but I found your issue at https://bugs.mojang.com/browse/MC-244164 and wanted to reach out for more information.

Myself and another person in [this Discord](https://caffeinemc.net/discord) in [this thread](https://discord.com/channels/602796788608401408/919300918795702292/919300920389554256) have encountered what appears to be the same issue as you. To try to track down the issue, could you share if you were using mods and if so, what they were?

**Comment by Airblader** [comment]
Hey there! Thanks for reaching out. Yes, we generally use Fabric and a couple of mods, but I verified all of this on a completely vanilla install without any mods whilst reproducing the issue for the JIRA issue. I'm happy to help in any way I can.

**Comment by Airblader** [comment]
Since the world download was taken WITH mods, though, it could still be relevant. I'll give you a list of mods in a few minutes.

**Comment by Airblader** [comment]
I joined the Discord, let's continue there.
