### ISSUE TITLE
i3blocks fails with exit1

### ISSUE THREAD

**Issue by lampensau** [Airblader/dotfiles-manjaro#4]
Hi,
I just wanted to try your i3bar setup but cant get your config working. What dependencies does it bring?

Would appreciate if you could tip me in the right direction.

Kind regards.

P.S. it even fails me with just one command of your .i3blocks.conf. The python script 'volume_control.py' seems to run fine (e.g. toggle mutes the Master) on itself, pavucontrol is present but something seems to be missing. BTW the logging of i3 is terrible :P

**Comment by lampensau** [comment]
god damn it, i didnt see the setup folder ...
Your i3 fork gives me lots of plesure, thx for your work!

**Comment by Airblader** [comment]
Sorry for the late reply, I'm out of the country at the moment. I can see you found the setup folder now. If anything still doesn't work, please let me know. The dependencies for i3blocks should be i3blocks (d'oh), xtitle, pavucontrol, iwgetid, acpi and gsimplecal.

I'll close this issue but please do feel free to keep commenting on it if you have any other questions!

**Comment by Airblader** [comment]
Oh, one more thing: i3 actually logs fairly well, but you might have to enable debug logging :) See http://i3wm.org/docs/debugging.html
