### ISSUE TITLE
manjaro-i3-openrc livecd (15.12) fails to suspend or shut down

### ISSUE THREAD

**Issue by Boruch-Baum** [Airblader/dotfiles-manjaro#5]
Hi, Ingo. I'm evaluating the livecd recently issued for manjaro-i3-openrc. it's not clear who might be the single address to notify of i3exit issues, so I found you here, and am guessing you might be the guy to mention trouble in getting the i3 version of manjaro to shut down or suspend.

The hardware environment is a 2014 Acer laptop, on which the xfce-openrc version of manjaro had suspended and shut down okay, installed onto the /dev/sda hard drive. This evaluation is running the liveCD environment off a usb stick on /dev/sdb.

Suspending from the desktop, using Mod+0 s: the screen blurs and locks the screen. No unlock found to work.

Suspending from the DM, using the icon on upper right: locks the screen. no recovery found. No unlock found to work.

Exiting from the desktop, using Mod+0 S, or from the DM using the icon on upper right: shutdown begins, but hangs at screen messages: "Remounting remaining filesystems read-only" "Remounting / read only"

**Comment by Airblader** [comment]
Hi, 

I think the best place for this is the Manjaro-i3 forum where the guys actually providing this spin can help you directly ( https://forum.manjaro.org/index.php?board=53.0). 

For i3 issues in general, you can use either the mailing list (see the i3 website under contact) or the i3wm subreddit which recently replaced the i3 faq page. However, this isn't an i3 issue so the Manjaro-i3 forums are the best place to ask for now. 

I myself don't use openrc and don't really know anything about it, so off the bet I can't really help, sorry.
