### ISSUE TITLE
What is slopsize.sh used for?

### ISSUE THREAD

**Issue by Fandekasp** [Airblader/dotfiles-manjaro#6]
SSIA. I've shamelessly stolen your config files for my own sytem, since I was lazy to re-invent the wheel. But there's some learning curve here :)

**Comment by Airblader** [comment]
It's used in my resize binding mode:

````
mode --pango_markup "$mode_resize" {
    # …
    bindsym s mode "default", exec --no-startup-id $HOME/scripts/slopsize.sh                      
    # …
}
```

It's used for floating windows. When a floating window is focused and you call the script, you can select some rectangle on your screen with the mouse and the window will then be resized / repositioned to take exactly the shape of that rectangle. So essentially, you can use it to place (floating) windows.

It, of course, requires `slop` to be installed.

**Comment by Airblader** [comment]
Just gonna close this, but don't let it stop you from commenting on this more if you have questions. :)

**Comment by Fandekasp** [comment]
That's awesome, I love it. Thanks a bunch ! If you ever want to come to Osaka, I owe you a beer :)

**Comment by Airblader** [comment]
I'll try to remember if I'm ever in the area ;)
