### ISSUE TITLE
front not font in dotfiles/.config/compton.conf

### ISSUE THREAD

**Issue by kingy9000** [Airblader/dotfiles-manjaro#7]
I noticed that you have an incorrect setting:
glx-copy-from-font = true it should instead be glx-copy-from-front = true
Notice the difference between font and front.

You can refer to the compton man page to see that there is no reference to the setting glx-copy-from-font but there is to glx-copy-from-f**r**ont.

Please let me know if I am wrong but as I failed to find any reference to the font setting I am assuming it's a minor typo in your config file.

**Comment by Airblader** [comment]
Right you are, thanks for the pointer. I can't believe people file bug reports against my dotfiles. =D

**Comment by kingy9000** [comment]
Least I could do for your contributions to i3. Will let you know if I notice anymore typos :P

**Comment by Airblader** [comment]
Yes, please do. :)
