### ISSUE TITLE
"Software Updater" window rendered as fully transparent

### ISSUE THREAD

**Issue by moritzheiber** [Airblader/dotfiles-manjaro#8]
So this is a bit of a bummer, since it's not reproducible 100% of the time.

System this is happening on: Ubuntu 15.10, latest updates, i3 4.12, compton 0.1~beta2-1 (latest release according to its repository).

When Software Updater picks up on new updates it usually spawns a window telling me which packages are outdated. Said window Is then rendered slightly transparent, I'd say 80% opaque. But when I hover my mouse cursor over it this turns into 0% opaque (or 100% transparent), essentially rendering the window completely useless (it appears to have vanished).

Any behavior, of the top of your head, that might be causing this?

Properties for a "normal" windows, where I couldn't reproduce these issues, are:

```
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x1, 0x1, 0x0, 0x0, 0x0
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
I3_FLOATING_WINDOW(CARDINAL) = 1
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x1e00001
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 439, 115
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 31457285, 31457286
_NET_WM_USER_TIME(CARDINAL) = 43697087
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1e00004
WM_CLIENT_LEADER(WINDOW): window id # 0x1e00001
_NET_WM_PID(CARDINAL) = 26355
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "paperclip"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 439 by 115
		program specified maximum size: 439 by 115
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "update-manager", "Update-manager"
WM_ICON_NAME(STRING) = "Software Updater"
_NET_WM_ICON_NAME(UTF8_STRING) = "Software Updater"
WM_NAME(STRING) = "Software Updater"
_NET_WM_NAME(UTF8_STRING) = "Software Updater"
```

**Comment by Airblader** [comment]
@moritzheiber 

> compton 0.1~beta2-1 (latest release according to its repository)

compton hasn't seen a release in years despite all the changes, so I'd urge you to install a source build first.

Also, I don't think this is related to my compton config. I'd say file this as a bug against compton or Ubuntu.
